### PR TITLE
Add rule to transform metadata

### PR DESCRIPTION
**Pull request by johnbradley**
Creating this Draft PR to show we could modify the workflow to use the https://github.com/hdr-bgnn/drexel_metadata/pull/6 changes. By adding the https://github.com/hdr-bgnn/drexel_metadata_formatter/tree/code-import.

Adds transform_metadata rule that transforms drexel metadata into a simpler format.
Uses https://github.com/hdr-bgnn/drexel_metadata_formatter to convert the metadata.

The changes use temporary containers built from the above two branches.  Before this could be merged those two branches need to be merged and releases created in the parent repos and we will use the ghcr.io repos.

I also used a different `crop_image` for bgnn metadata compatibility.

### CODE REVIEW

**Comment by thibaulttabarin** [comment]
Now, we have updated the crop and have a new release we should update the crop_image.smk with 
    container:
        'docker://ghcr.io/hdr-bgnn/crop_image:0.0.4'

**Comment by thibaulttabarin** [comment]
Same comment as for segment_image rule, new container
    container:
        'docker://ghcr.io/hdr-bgnn/bgnn-trait-segmentation:0.0.6'

**Comment by johnbradley** [comment]
I was able to run the workflow with the latest code. 
Still remaining for this PR are two rules using temporary containers. 
The `create_morphological_analysis` step needs to be updated to use a permanent container once
https://github.com/hdr-bgnn/Morphology-analysis/pull/36 is merged and a release created. 
The `generate_metadata` step needs to be updated to use a permanent container once https://github.com/hdr-bgnn/drexel_metadata/pull/6 is merged and a release created.

**Comment by johnbradley** [comment]
Closing this PR in favor of a simpler version via PR #41.

**Pull request closed without merging**
