### PR TITLE
Transforms metadata and streamlines the workflow

### LINKED ISSUE #40: Move morphology out to a more appropriate location
The [morphology component](https://github.com/hdr-bgnn/BGNN_Snakemake/blob/84e3604a6f767c43b31259237ab1ffc61bac3be8/workflow/rules/create_morphological_analysis.smk#L1-L14) is rather specific to the https://github.com/hdr-bgnn/Minnow_Segmented_Traits repo. Moving the morphology component out will make this workflow is more generic in nature.

### PR DESCRIPTION
**Pull request by johnbradley**
Adds rule to transform drexel_metadata output into a format compatible with the other tools.
Updates to latest tool containers to be compatible with various changes to the tools.
Removes morphology step so this workflow will be more generic.

Fixes #40

### CODE REVIEW

**Review by hlapp — APPROVED** [review]
LGTM 👍

**Comment by meghalithic** [comment]
@johnbradley do we still get a presence/absence matrix?

**Comment by johnbradley** [comment]
> @johnbradley do we still get a presence/absence matrix?

@megbalk No. The change here removes the morphology step that is specific to minnow traits. The last step in the core workflow is ML segmentation. The idea is choosing or creating a morphology step is left to the domain scientist that reuses this workflow.

---

To use the presence/absence files created via [hdr-bgnn/Morphology-analysis](https://github.com/hdr-bgnn/Morphology-analysis) a rule similar to the following would need to be added to the domain scientist's Snakefile:
```
rule create_morphological_analysis:
    input:
        image = 'Segmented/{image}_segmented.png',
        metadata = 'Metadata/{image}.json'
    output: 'Morphology/Presence/{image}_presence.json'
    log: 'logs/create_morphological_analysis_{image}.log'
    container:
        "docker://ghcr.io/hdr-bgnn/morphology-analysis/morphology:0.3.0"
    shell:
        'Morphology_main.py {input.image} {output} > {log} 2>&1'
```
---

[This code](https://github.com/hdr-bgnn/Minnow_Segmented_Traits/blob/a90871809dc267516b4ecb94a518c7b49090401a/workflow/Snakefile#L74-L83) in the Minnow_Segmented_Traits streamline branch adds the `create_morphological_analysis` rule to create the presence/absence data using the hdr-bgnn/Morphology-analysis code. (We do need to update to the latest container there).

**Comment by meghalithic** [comment]
We still want the output of the presence / absence matrix to do our preliminary analyses and set up for the next paper. Can we add that back in?

**Comment by johnbradley** [comment]
> We still want the output of the presence / absence matrix to do our preliminary analyses and set up for the next paper. Can we add that back in?

@megbalk Perhaps I am misunderstanding, but the presence / absence data is already available in the Minnow_Segmented_Traits streamline branch. Due to [this code](https://github.com/hdr-bgnn/Minnow_Segmented_Traits/blob/a90871809dc267516b4ecb94a518c7b49090401a/workflow/Snakefile#L74-L83) in that repo. We aren't deleting this morphology rule just moving it from BGNN_Core_Workflow to  Minnow_Segmented_Traits.

**Comment by hlapp** [comment]
Indeed, as @johnbradley says, because it is no longer considered a part of the _core workflow_, which is what this repo is about. That doesn't mean it can be part of a domain science composite workflow that builds on top of the core workflow, such as Minnow Traits demonstrates.

**Comment by meghalithic** [comment]
ah ok, I was confused, sorry!

**Review by meghalithic — APPROVED** [review]

**Pull request merged**
